### ISSUE TITLE
Unnamed namespace causes ODR violations in C++

### ISSUE THREAD

**Issue by jwakely** [lemire/fastmod#6]
Putting everything in an unnamed namespace means that your header can't safely be used by templates or other code in headers. If a function template or inline function that uses `fastmod` is used in two different translation units the two copies of the function will call different versions of `fastmod` in different unnamed namespaces, which breaks the One-Definition Rule and so has undefined behaviour. With C++20 Modules this is likely to be diagnosed and fail to compile.

**Comment by lemire** [comment]
Given that we want this code to work in C, and want to be as portable as possible, what do you propose as a better design?

**Comment by jwakely** [comment]
Just don't use an anonymous namespace.

**Comment by lemire** [comment]
@jwakely If you include the header in more than one location in your project, then you are going to get several definitions for the same functions.

My own code called the function 'static' (C). This works, obviously.

However, since C++11, C++ purists want to drop 'static' in favor of unnamed namespace, which is what we have here.

So... I don't think we can drop the unnamed namespace and leave it at that. If you think I am wrong, please elaborate.

**Comment by jwakely** [comment]
Oh, I assumed the functions were already `inline`. That's the solution for C++. No unnamed namespace, but `inline`. Now they can be included in multiple files and defined multiple times, but you get identical definitions in each.

**Comment by lemire** [comment]
It appears to fail with errors like...

```
include/fastmod.h: In function ‘uint32_t fastmod::fastmod(uint32_t)’:
include/fastmod.h:174:26: error: ‘v’ declared as an ‘inline’ variable
     FASTMOD_API uint64_t v = computeM_u32(d);
```

**Comment by lemire** [comment]
Closed with a PR from @jwakely
